# webforJ configuration
webforj.entry=com.webforj.tutorial.Application
webforj.debug=true
webforj.devtools.craftforj.enabled=true
webforj.devtools.livereload.enabled=true

# Hot reload configuration
server.shutdown=immediate

# H2 Database configuration
spring.datasource.url=jdbc:h2:mem:testdb

# JPA configuration
spring.jpa.hibernate.ddl-auto=update

