# webforJ configuration
webforj.entry=com.webforj.tutorial.Application
webforj.debug=true
webforj.devtools.craftforj.enabled=true
webforj.devtools.livereload.enabled=true

# Hot reload configuration
server.shutdown=immediate
