# Spring Boot configuration
spring.application.name=CustomerApplication

# Server configuration
server.shutdown=immediate
server.port=8080

# webforJ DevTools configuration
spring.devtools.livereload.enabled=false
webforj.devtools.livereload.enabled=true
webforj.devtools.livereload.static-resources-enabled=true
webforj.devtools.browser.open=true
webforj.debug=true
webforj.entry = com.webforj.tutorial.Application

# H2 Database configuration
# spring.datasource.url=jdbc:h2:mem:testdb
# spring.datasource.driverClassName=org.h2.Driver
# spring.datasource.username=sa
# spring.datasource.password=

# JPA configuration
# spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
# spring.jpa.hibernate.ddl-auto=update

# H2 Console (optional - for development)
# spring.h2.console.enabled=true
# spring.h2.console.path=/h2-console